account:
  auto_create: True
  gmlevel: 3
  realm_id: -1 # or specify RealmID
  has_boost: 1

authserver:
  host: 0.0.0.0
  port: 3724

worldserver:
  host: 0.0.0.0
  port: 8086

proxyserver: 
  auth_host: 0.0.0.0
  auth_port: 3722
  auth_remote_host: 192.168.11.30
  auth_remote_port: 3724
  world_host: 0.0.0.0
  world_port: 8084
  world_remote_host: 192.168.11.30
  world_remote_port: 8085

apiserver:
  host: 0.0.0.0
  port: 9002

crypto:
  N: 894B645E89E1535BBDAD5B8B290650530801B18EBFBF5E8FAB3C82872A3E9BB7
  g: 7

database:
  host: 192.168.11.30
  port: 3336
  user: root
  password: pwd
  charset: utf8mb4
  auth: auth
  world: world
  characters: characters

Logging:
  # Specify the logging levels as names (comma-separated) or use "All" for all levels.
  # Levels:
  #   - None
  #   - Success
  #   - Information
  #   - Anticheat
  #   - Warning
  #   - Error
  #   - Debug
  #   - Script
  #   - Package
  #   - All
  # Example:
  #  logging_levels: Information, Success, Debug, Script, Error
  #  logging_levels: All
  logging_levels: All
  log_file: auth.log
  world_file: world.log

  # Define the date format for log timestamps.
  # Examples of formats:
  # - English: "[%Y-%m-%d %H:%M:%S]"
  # - American: "[%m/%d/%Y %I:%M:%S %p]"
  # - Russian: "[%d.%m.%Y %H:%M:%S]"
  # - Swedish: "[%Y-%m-%d %H:%M:%S]"
  date_format: "[%Y-%m-%d %H:%M:%S]"
  
  # Display raw data from opcpde(s)
  # Display client opcode yell and server respons.
  # ex.  4aa, 1a9a 
  opcodes:
  # opcodes: 160a, 1e1b, 11c3
  # opcodes: 4909, b200, 19c1, 31c, 18b2, 162b, 11c3

opcodes:
  max: 0x1FFF
  number_handlers: 0x7FFF
  compressed_mask: 0x8000
