authserver:
  host: 0.0.0.0
  port: 3724
  builds: 18141

crypto:
 N: 894B645E89E1535BBDAD5B8B290650530801B18EBFBF5E8FAB3C82872A3E9BB7
 g: 7
 # For testing purpose, it's the only uniqe values then creating proof
 b: 979CD6A6747EDA0BFDF842375339ADA421CBC1
 unk3: 8F792557C85767DB61F6E2775C628EB5
 ServerEncryptionKey: bytes([0x08, 0xF1, 0x95, 0x9F, 0x47, 0xE5, 0xD2, 0xDB, 0xA1, 0x3D, 0x77, 0x8F, 0x3F, 0x3E, 0xE7, 0x00])
 ServerDecryptionKey: bytes([0x40, 0xAA, 0xD3, 0x92, 0x26, 0x71, 0x43, 0x47, 0x3A, 0x31, 0x08, 0xA6, 0xE7, 0xDC, 0x98, 0x2A])

database:
  host: 192.168.11.30
  port: 3336
  user: root
  password: pwd
  charset: utf8mb4
  
Logging:
  # Debug level values (you can combine them as a mask):
  # None = 0x00 (0)
  # Success = 0x01 (1)
  # Information = 0x02 (2)
  # Anticheat = 0x04 (4)
  # Warning = 0x08 (8)
  # Error = 0x10 (16)
  # Debug = 0x20 (32)
  # Script = 0x40 (64)
  #
  # All = 0x7f (127, the sum of all)
  logging_mask: 0x7f
  log_file: auth.log
  world_file: world.log

opcodes:
  max: 0x1FFF
  number_handlers: 0x7FFF
  compressed_mask: 0x8000