authserver:
  host: 0.0.0.0
  port: 3724

crypto:
 N: 894B645E89E1535BBDAD5B8B290650530801B18EBFBF5E8FAB3C82872A3E9BB7
 g: 7

database:
  host: 192.168.11.30
  port: 3336
  user: root
  password: pwd
  charset: utf8mb4
  
Logging:
  # Debug level values (you can combine them as a mask):
  # None = 0x00 (0)
  # Success = 0x01 (1)
  # Information = 0x02 (2)
  # Anticheat = 0x04 (4)
  # Warning = 0x08 (8)
  # Error = 0x10 (16)
  # Debug = 0x20 (32)
  # Script = 0x40 (64)
  #
  # All = 0x7f (127, the sum of all)
  logging_mask: 0x7f
  auth_file: auth.log
  world_file: world.log
