#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations

UPDATE_TYPE_VALUES = 0
UPDATE_TYPE_CREATE_OBJECT = 1
UPDATE_TYPE_CREATE_OBJECT2 = 2
UPDATE_TYPE_OUT_OF_RANGE_OBJECTS = 3

OBJECT_FIELD_GUID_LOW = 0
OBJECT_FIELD_GUID_HIGH = 1
OBJECT_FIELD_TYPE = 4
OBJECT_FIELD_ENTRY = 5
OBJECT_FIELD_DYNAMIC_FLAGS = 6
OBJECT_FIELD_SCALE_X = 7
