#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations

from server.modules.handlers.world.protocol.update_object.common import (
    OBJECT_FIELD_DYNAMIC_FLAGS,
    OBJECT_FIELD_ENTRY,
    OBJECT_FIELD_GUID_HIGH,
    OBJECT_FIELD_GUID_LOW,
    OBJECT_FIELD_SCALE_X,
    OBJECT_FIELD_TYPE,
)

CREATURE_VISIBILITY_RADIUS = 120.0
CREATURE_PACKET_LIMIT = 200
CREATURE_CREATE_FLAGS = bytes.fromhex("200000000029CC00000800004F")
CREATURE_UPDATE_COUNT = 1
CREATURE_UPDATE_TYPE = 2
CREATURE_OBJECT_TYPE = 3
CREATURE_MASK_BLOCKS = 5

UNIT_FIELD_BYTES_0 = 30
UNIT_FIELD_BYTES_1 = 31
UNIT_FIELD_HEALTH = 33
UNIT_FIELD_MAX_HEALTH = 39
UNIT_FIELD_POWER_1 = 40
UNIT_FIELD_LEVEL = 55
UNIT_FIELD_FACTION_TEMPLATE = 57
UNIT_FIELD_FLAGS = 61
UNIT_FIELD_NPC_FLAGS = 87
UNIT_FIELD_BOUNDING_RADIUS = 67
UNIT_FIELD_COMBAT_REACH = 68
UNIT_FIELD_DISPLAY_ID = 69
UNIT_FIELD_NATIVE_DISPLAY_ID = 70
UNIT_FIELD_MOUNT_DISPLAY_ID = 71
UNIT_FIELD_HOVER_HEIGHT = 154

CREATURE_OBJECT_TYPE_FIELD_VALUE = 9
CREATURE_DYNAMIC_FLAGS_DEFAULT = 0
CREATURE_SCALE_DEFAULT = 1.0
CREATURE_BYTES_0_DEFAULT = 33554688
CREATURE_BYTES_1_DEFAULT = 1
CREATURE_HEALTH_DEFAULT = 17
CREATURE_POWER_DEFAULT = 1000
CREATURE_LEVEL_DEFAULT = 1
CREATURE_FACTION_TEMPLATE_DEFAULT = 188
CREATURE_FLAGS_DEFAULT = 768
CREATURE_FLAGS_3_DEFAULT = 4194304
CREATURE_POWER_REGEN_DEFAULT = 2000
CREATURE_BOUNDING_RADIUS_DEFAULT = 0.05
CREATURE_COMBAT_REACH_DEFAULT = 0.15
CREATURE_MOUNT_DISPLAY_ID_DEFAULT = 0
CREATURE_UNIT_MOD_DEFAULT = 1.0
CREATURE_HOVER_HEIGHT_DEFAULT = 1.0
CREATURE_FIELD_128_DEFAULT = 1
CREATURE_FIELD_157_DEFAULT = 1

__all__ = [name for name in globals() if name.isupper()]
