#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations

from server.modules.handlers.world.protocol.update_object.common import (
    OBJECT_FIELD_DYNAMIC_FLAGS,
    OBJECT_FIELD_ENTRY,
    OBJECT_FIELD_GUID_HIGH,
    OBJECT_FIELD_GUID_LOW,
    OBJECT_FIELD_SCALE_X,
    OBJECT_FIELD_TYPE,
)

GAMEOBJECT_VISIBILITY_RADIUS = 120.0
GAMEOBJECT_PACKET_LIMIT = 200
GAMEOBJECT_CREATE_FLAGS = bytes.fromhex("000000030040")
GAMEOBJECT_UPDATE_COUNT = 1
GAMEOBJECT_UPDATE_TYPE = 1
GAMEOBJECT_VALUES_UPDATE_TYPE = 0
GAMEOBJECT_OBJECT_TYPE = 5
GAMEOBJECT_MASK_BLOCKS = 1
GAMEOBJECT_DYNAMIC_MASK_BLOCKS = 0
GAMEOBJECT_MOVEMENT_BLOCK_UINT32 = 0

GAMEOBJECT_FIELD_DISPLAY_ID = 10
GAMEOBJECT_FIELD_FLAGS = 11
GAMEOBJECT_FIELD_ROTATION_START = 12
GAMEOBJECT_FIELD_FACTION = 16
GAMEOBJECT_FIELD_LEVEL = 17
GAMEOBJECT_FIELD_PERCENT_HEALTH = 18
GAMEOBJECT_FIELD_STATE_SPELL_VISUAL_ID = 19
GAMEOBJECT_ROTATION_COMPONENT_KEYS = ("rotation0", "rotation1", "rotation2", "rotation3")
PACKED_QUATERNION_X_SCALE = 2_097_152
PACKED_QUATERNION_YZ_SCALE = 1_048_576
QUATERNION_EPSILON = 0.000001
QUATERNION_UNIT_EPSILON = 0.00001

GAMEOBJECT_TYPE_TRANSPORT = 11
GAMEOBJECT_TYPE_MO_TRANSPORT = 15
GO_FLAG_TRANSPORT = 0x00000008
GO_STATE_ACTIVE = 0
GO_STATE_READY = 1
GO_HEALTH_FULL = 0xFF

UPDATEFLAG_NONE = 0x0000
UPDATEFLAG_SELF = 0x0001
UPDATEFLAG_TRANSPORT = 0x0002
UPDATEFLAG_HAS_TARGET = 0x0004
UPDATEFLAG_LIVING = 0x0008
UPDATEFLAG_STATIONARY_POSITION = 0x0010
UPDATEFLAG_VEHICLE = 0x0020
UPDATEFLAG_GO_TRANSPORT_POSITION = 0x0040
UPDATEFLAG_ROTATION = 0x0080
UPDATEFLAG_ANIMKITS = 0x0100


def build_gameobject_create_flags(update_flags: int) -> bytes:
    """Pack SkyFire-style movement-update presence bits for a non-living GameObject."""
    flags = int(update_flags)
    bits: list[int] = [
        0,  # UPDATEFLAG_HAS_GAMEOBJECT
        1 if (flags & UPDATEFLAG_ANIMKITS) else 0,
        1 if (flags & UPDATEFLAG_LIVING) else 0,
        0,  # UPDATEFLAG_SCENE_LOCAL_SCRIPT_DATA
        0,
    ]
    bits.extend([0] * 22)  # UPDATEFLAG_TRANSPORT_FRAME_COUNT
    bits.extend(
        [
            1 if (flags & UPDATEFLAG_VEHICLE) else 0,
            0,  # UNK 1044
            0,
            1 if (flags & UPDATEFLAG_TRANSPORT) else 0,
            1 if (flags & UPDATEFLAG_ROTATION) else 0,
            0,
            1 if (flags & UPDATEFLAG_SELF) else 0,
            1 if (flags & UPDATEFLAG_HAS_TARGET) else 0,
            0,  # UPDATEFLAG_SCENE_OBJECT
            0,  # UPDATEFLAG_SCENE_PENDING_INSTANCES
            0,
            0,  # UPDATEFLAG_HAS_AREATRIGGER
            1 if (flags & UPDATEFLAG_GO_TRANSPORT_POSITION) else 0,
            0,  # UPDATEFLAG_REPLACE_YOU
            1 if (flags & UPDATEFLAG_STATIONARY_POSITION) else 0,
        ]
    )

    packed = bytearray()
    for offset in range(0, len(bits), 8):
        chunk = bits[offset : offset + 8]
        value = 0
        for index, bit in enumerate(chunk):
            value |= (int(bit) & 1) << (7 - index)
        packed.append(value)
    return bytes(packed)

__all__ = [
    "OBJECT_FIELD_DYNAMIC_FLAGS",
    "OBJECT_FIELD_ENTRY",
    "OBJECT_FIELD_GUID_HIGH",
    "OBJECT_FIELD_GUID_LOW",
    "OBJECT_FIELD_SCALE_X",
    "OBJECT_FIELD_TYPE",
    "GAMEOBJECT_VISIBILITY_RADIUS",
    "GAMEOBJECT_PACKET_LIMIT",
    "GAMEOBJECT_CREATE_FLAGS",
    "GAMEOBJECT_UPDATE_COUNT",
    "GAMEOBJECT_UPDATE_TYPE",
    "GAMEOBJECT_VALUES_UPDATE_TYPE",
    "GAMEOBJECT_OBJECT_TYPE",
    "GAMEOBJECT_MASK_BLOCKS",
    "GAMEOBJECT_DYNAMIC_MASK_BLOCKS",
    "GAMEOBJECT_MOVEMENT_BLOCK_UINT32",
    "GAMEOBJECT_FIELD_DISPLAY_ID",
    "GAMEOBJECT_FIELD_FLAGS",
    "GAMEOBJECT_FIELD_ROTATION_START",
    "GAMEOBJECT_FIELD_FACTION",
    "GAMEOBJECT_FIELD_LEVEL",
    "GAMEOBJECT_FIELD_PERCENT_HEALTH",
    "GAMEOBJECT_FIELD_STATE_SPELL_VISUAL_ID",
    "GAMEOBJECT_ROTATION_COMPONENT_KEYS",
    "PACKED_QUATERNION_X_SCALE",
    "PACKED_QUATERNION_YZ_SCALE",
    "QUATERNION_EPSILON",
    "QUATERNION_UNIT_EPSILON",
    "GAMEOBJECT_TYPE_TRANSPORT",
    "GAMEOBJECT_TYPE_MO_TRANSPORT",
    "GO_FLAG_TRANSPORT",
    "GO_STATE_ACTIVE",
    "GO_STATE_READY",
    "GO_HEALTH_FULL",
    "UPDATEFLAG_NONE",
    "UPDATEFLAG_SELF",
    "UPDATEFLAG_TRANSPORT",
    "UPDATEFLAG_HAS_TARGET",
    "UPDATEFLAG_LIVING",
    "UPDATEFLAG_STATIONARY_POSITION",
    "UPDATEFLAG_VEHICLE",
    "UPDATEFLAG_GO_TRANSPORT_POSITION",
    "UPDATEFLAG_ROTATION",
    "UPDATEFLAG_ANIMKITS",
    "build_gameobject_create_flags",
]
